"""Workspace-provider lifecycle and registry support."""

from cli_agent_orchestrator.workspace_providers.registry import (
    ProviderToolAccessWorkspaceProvider,
    UnknownWorkspaceProviderError,
    WorkspaceProvider,
    WorkspaceProviderConfigError,
    WorkspaceProviderRegistry,
    default_workspace_provider_registry,
    initialize_enabled_workspace_providers,
    is_workspace_provider_enabled,
    load_enabled_provider_tool_access_policies,
    load_enabled_workspace_providers,
    load_provider_tool_access_policies,
    resolve_agent_identity_for_runtime,
    workspace_provider_config_exists,
)
from cli_agent_orchestrator.workspace_providers.tool_access import (
    ProviderMediatedToolDefinition,
    ProviderMediatedToolRuntimeGenerationDescriptor,
    ProviderMediatedToolSurfaceDescriptor,
    ProviderToolAccess,
    ProviderToolAccessConfigError,
    ProviderToolAccessIssue,
    ProviderToolAccessPolicy,
    ProviderToolAccessRequest,
    ProviderToolHandler,
    ProviderToolHookDefinition,
    ProviderToolHookHandler,
    ProviderToolHookPhase,
    ProviderToolInvocationContext,
    ProviderToolPreCallResult,
    normalize_provider_tool_access,
)

__all__ = [
    "ProviderMediatedToolDefinition",
    "ProviderMediatedToolRuntimeGenerationDescriptor",
    "ProviderMediatedToolSurfaceDescriptor",
    "ProviderToolAccess",
    "ProviderToolAccessConfigError",
    "ProviderToolAccessIssue",
    "ProviderToolAccessPolicy",
    "ProviderToolAccessRequest",
    "ProviderToolAccessWorkspaceProvider",
    "ProviderToolHandler",
    "ProviderToolHookHandler",
    "ProviderToolHookDefinition",
    "ProviderToolHookPhase",
    "ProviderToolInvocationContext",
    "ProviderToolPreCallResult",
    "WorkspaceProvider",
    "WorkspaceProviderConfigError",
    "WorkspaceProviderRegistry",
    "UnknownWorkspaceProviderError",
    "default_workspace_provider_registry",
    "initialize_enabled_workspace_providers",
    "is_workspace_provider_enabled",
    "load_enabled_workspace_providers",
    "load_enabled_provider_tool_access_policies",
    "load_provider_tool_access_policies",
    "normalize_provider_tool_access",
    "resolve_agent_identity_for_runtime",
    "workspace_provider_config_exists",
]
