"""Database infrastructure facade.

This module owns shared SQLAlchemy setup and preserves the historic
``cli_agent_orchestrator.clients.database`` import surface. Domain-specific
persistence lives in focused owner modules such as ``terminal_store``,
``inbox_store``, ``baton_store``, and ``flow_store``.
"""

from __future__ import annotations

from cli_agent_orchestrator.clients.database_core import Base, SessionLocal, engine

# Import domain owner surfaces after Base exists so models register metadata.
from cli_agent_orchestrator.clients.terminal_store import (  # noqa: E402
    TerminalModel,
    create_terminal,
    delete_terminal,
    delete_terminals_by_session,
    get_terminal_metadata,
    list_all_terminals,
    list_terminals_by_session,
    update_last_active,
)
from cli_agent_orchestrator.clients.inbox_store import (  # noqa: E402
    INBOX_NOTIFICATION_TARGET_KIND_MESSAGE,
    INBOX_NOTIFICATION_TARGET_ROLE_PRIMARY,
    InboxMessageModel,
    InboxNotificationModel,
    InboxNotificationTargetModel,
    create_inbox_delivery,
    create_inbox_message_record,
    create_inbox_notification,
    create_inbox_notification_event,
    get_inbox_delivery,
    get_oldest_pending_inbox_delivery,
    inbox_delivery_from_models,
    inbox_message_record_from_model,
    inbox_notification_from_model,
    inbox_notification_target_from_model,
    list_inbox_deliveries,
    list_pending_inbox_deliveries_for_effective_source,
    list_pending_inbox_notifications,
    move_pending_inbox_notifications,
    update_inbox_notification_receiver,
    update_inbox_notification_status,
    update_inbox_notification_statuses,
)
from cli_agent_orchestrator.clients.presence_store import (  # noqa: E402
    AgentRuntimeNotificationModel,
    MonitoringSessionModel,
    PresenceInboxNotificationModel,
    PresenceMessageModel,
    PresenceThreadModel,
    PresenceWorkItemModel,
    ProcessedProviderEventModel,
)
from cli_agent_orchestrator.clients.baton_store import (  # noqa: E402
    BatonEventModel,
    BatonModel,
    baton_event_from_model,
    baton_from_model,
    get_baton_record,
    list_baton_events,
    list_batons,
    list_batons_held_by,
)
from cli_agent_orchestrator.clients.flow_store import (  # noqa: E402
    FlowModel,
    create_flow,
    delete_flow,
    flow_from_model,
    get_flow,
    get_flows_to_run,
    list_flows,
    update_flow_enabled,
    update_flow_run_times,
)
from cli_agent_orchestrator.clients.database_migrations import (  # noqa: E402
    _migrate_drop_legacy_inbox_notification_ids,
    _migrate_drop_legacy_inbox_table,
    _migrate_drop_monitoring_session_peers,
    _migrate_ensure_agent_runtime_tables,
    _migrate_ensure_baton_tables,
    _migrate_ensure_presence_tables,
    _migrate_ensure_semantic_inbox_tables,
    init_db,
)

__all__ = [
    "AgentRuntimeNotificationModel",
    "Base",
    "BatonEventModel",
    "BatonModel",
    "FlowModel",
    "INBOX_NOTIFICATION_TARGET_KIND_MESSAGE",
    "INBOX_NOTIFICATION_TARGET_ROLE_PRIMARY",
    "InboxMessageModel",
    "InboxNotificationModel",
    "InboxNotificationTargetModel",
    "MonitoringSessionModel",
    "PresenceInboxNotificationModel",
    "PresenceMessageModel",
    "PresenceThreadModel",
    "PresenceWorkItemModel",
    "ProcessedProviderEventModel",
    "SessionLocal",
    "TerminalModel",
    "_migrate_drop_legacy_inbox_notification_ids",
    "_migrate_drop_legacy_inbox_table",
    "_migrate_drop_monitoring_session_peers",
    "_migrate_ensure_agent_runtime_tables",
    "_migrate_ensure_baton_tables",
    "_migrate_ensure_presence_tables",
    "_migrate_ensure_semantic_inbox_tables",
    "baton_event_from_model",
    "baton_from_model",
    "create_flow",
    "create_inbox_delivery",
    "create_inbox_message_record",
    "create_inbox_notification",
    "create_inbox_notification_event",
    "create_terminal",
    "delete_flow",
    "delete_terminal",
    "delete_terminals_by_session",
    "engine",
    "flow_from_model",
    "get_baton_record",
    "get_flow",
    "get_flows_to_run",
    "get_inbox_delivery",
    "get_oldest_pending_inbox_delivery",
    "get_terminal_metadata",
    "inbox_delivery_from_models",
    "inbox_message_record_from_model",
    "inbox_notification_from_model",
    "inbox_notification_target_from_model",
    "init_db",
    "list_all_terminals",
    "list_baton_events",
    "list_batons",
    "list_batons_held_by",
    "list_flows",
    "list_inbox_deliveries",
    "list_pending_inbox_deliveries_for_effective_source",
    "list_pending_inbox_notifications",
    "list_terminals_by_session",
    "move_pending_inbox_notifications",
    "update_flow_enabled",
    "update_flow_run_times",
    "update_inbox_notification_receiver",
    "update_inbox_notification_status",
    "update_inbox_notification_statuses",
    "update_last_active",
]
