"""Database infrastructure facade.

This module owns shared SQLAlchemy setup and preserves the historic
``cli_agent_orchestrator.clients.database`` import surface. Domain-specific
persistence lives in focused owner modules such as ``terminal_store``,
``inbox_store``, ``baton_store``, and ``flow_store``.
"""

from __future__ import annotations

from cli_agent_orchestrator.clients.baton_store import (  # noqa: E402
    BatonEventModel,
    BatonModel,
    baton_event_from_model,
    baton_from_model,
    get_baton_record,
    list_baton_events,
    list_batons,
    list_batons_held_by,
)
from cli_agent_orchestrator.clients.cao_event_store import (  # noqa: E402
    CaoEventParticipantRecord,
    CaoEventRecord,
    get_cao_event,
    list_cao_event_participants_by_agent,
    list_cao_events_by_agent,
    list_cao_events_by_causation_id,
    list_cao_events_by_correlation_id,
    list_cao_events_by_event_name,
    list_cao_events_by_source,
)
from cli_agent_orchestrator.clients.database_core import Base, SessionLocal, engine
from cli_agent_orchestrator.clients.database_migrations import (  # noqa: E402
    _migrate_drop_legacy_inbox_notification_ids,
    _migrate_drop_legacy_inbox_table,
    _migrate_drop_linear_and_provider_conversation_tables,
    _migrate_drop_monitoring_session_peers,
    _migrate_drop_removed_linear_cao_events,
    _migrate_ensure_agent_runtime_tables,
    _migrate_ensure_baton_tables,
    _migrate_ensure_cao_event_tables,
    _migrate_ensure_semantic_inbox_tables,
    _migrate_ensure_workspace_context_tables,
    init_db,
)
from cli_agent_orchestrator.clients.flow_store import (  # noqa: E402
    FlowModel,
    create_flow,
    delete_flow,
    flow_from_model,
    get_flow,
    get_flows_to_run,
    list_flows,
    update_flow_enabled,
    update_flow_run_times,
)
import cli_agent_orchestrator.inbox  # noqa: E402,F401
from cli_agent_orchestrator.clients.runtime_notification_store import (  # noqa: E402
    AgentRuntimeNotificationModel,
    MonitoringSessionModel,
)

# Import domain owner surfaces after Base exists so models register metadata.
from cli_agent_orchestrator.clients.terminal_store import (  # noqa: E402
    TerminalAgentAlreadyRunningError,
    TerminalModel,
    create_terminal,
    delete_terminal,
    delete_terminals_by_session,
    get_terminal_metadata,
    list_all_terminals,
    list_terminals_by_agent,
    list_terminals_by_session,
    update_last_active,
)
from cli_agent_orchestrator.clients.workspace_context_store import (  # noqa: E402
    ContextWorkspaceModel,
    WorkspaceContextModel,
    WorkspaceContextObjectMappingModel,
    attach_workspace_context_object,
    default_workspace_context_id,
    ensure_context_workspace,
    ensure_default_workspace_context,
    ensure_workspace_context_for_boundary,
    get_context_workspace,
    get_workspace_context_for_object,
    set_context_workspace_active_terminal,
    workspace_context_id_for_boundary,
)

__all__ = [
    "AgentRuntimeNotificationModel",
    "Base",
    "BatonEventModel",
    "BatonModel",
    "CaoEventParticipantRecord",
    "CaoEventRecord",
    "FlowModel",
    "MonitoringSessionModel",
    "SessionLocal",
    "TerminalModel",
    "TerminalAgentAlreadyRunningError",
    "ContextWorkspaceModel",
    "WorkspaceContextModel",
    "WorkspaceContextObjectMappingModel",
    "_migrate_drop_legacy_inbox_notification_ids",
    "_migrate_drop_legacy_inbox_table",
    "_migrate_drop_linear_and_provider_conversation_tables",
    "_migrate_drop_monitoring_session_peers",
    "_migrate_drop_removed_linear_cao_events",
    "_migrate_ensure_agent_runtime_tables",
    "_migrate_ensure_baton_tables",
    "_migrate_ensure_cao_event_tables",
    "_migrate_ensure_semantic_inbox_tables",
    "_migrate_ensure_workspace_context_tables",
    "baton_event_from_model",
    "baton_from_model",
    "create_flow",
    "create_terminal",
    "attach_workspace_context_object",
    "delete_flow",
    "delete_terminal",
    "delete_terminals_by_session",
    "default_workspace_context_id",
    "ensure_context_workspace",
    "ensure_default_workspace_context",
    "ensure_workspace_context_for_boundary",
    "engine",
    "flow_from_model",
    "get_baton_record",
    "get_cao_event",
    "get_flow",
    "get_flows_to_run",
    "get_terminal_metadata",
    "get_context_workspace",
    "get_workspace_context_for_object",
    "init_db",
    "list_all_terminals",
    "list_terminals_by_agent",
    "list_baton_events",
    "list_batons",
    "list_batons_held_by",
    "list_cao_event_participants_by_agent",
    "list_cao_events_by_agent",
    "list_cao_events_by_causation_id",
    "list_cao_events_by_correlation_id",
    "list_cao_events_by_event_name",
    "list_cao_events_by_source",
    "list_flows",
    "list_terminals_by_session",
    "update_flow_enabled",
    "update_flow_run_times",
    "update_last_active",
    "set_context_workspace_active_terminal",
    "workspace_context_id_for_boundary",
]
