"""Generate frontend TypeScript constants for backend CAO event type keys."""

from __future__ import annotations

import ast
import importlib
import re
from pathlib import Path

from cli_agent_orchestrator.events.serialization import event_type_key

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src" / "cli_agent_orchestrator"
OUTPUT_PATH = REPO_ROOT / "web" / "src" / "generated" / "caoEventTypeKeys.ts"


def main() -> None:
    constants = _event_type_constants()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(_render_typescript(constants), encoding="utf-8")


def _event_type_constants() -> dict[str, str]:
    constants: dict[str, str] = {}
    for module_name, tuple_name in _cao_event_tuple_exports():
        module = importlib.import_module(module_name)
        event_types = getattr(module, tuple_name)
        for event_type in event_types:
            constant_name = _constant_name(event_type.__name__)
            type_key = event_type_key(event_type)
            existing = constants.get(constant_name)
            if existing is not None and existing != type_key:
                raise RuntimeError(f"Duplicate generated CAO event constant: {constant_name}")
            constants[constant_name] = type_key
    return dict(sorted(constants.items()))


def _cao_event_tuple_exports() -> tuple[tuple[str, str], ...]:
    exports: list[tuple[str, str]] = []
    for path in sorted(SRC_ROOT.rglob("*.py")):
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        for node in tree.body:
            if not isinstance(node, ast.Assign):
                continue
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id.endswith("_CAO_EVENTS"):
                    exports.append((_module_name(path), target.id))
    return tuple(exports)


def _module_name(path: Path) -> str:
    relative = path.relative_to(REPO_ROOT / "src").with_suffix("")
    return ".".join(relative.parts)


def _constant_name(class_name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", class_name).upper()


def _render_typescript(constants: dict[str, str]) -> str:
    lines: list[str] = [
        "// Generated by scripts/generate_cao_event_type_keys.py.",
        "// Do not edit by hand.",
        "",
    ]
    for name, value in constants.items():
        lines.append(f"export const {name} = {value!r} as const")
    lines.extend(
        [
            "",
            "export const CAO_EVENT_TYPE_KEYS = {",
            *[f"  {name}," for name in constants],
            "} as const",
            "",
            "export type CaoEventTypeKey = typeof CAO_EVENT_TYPE_KEYS[keyof typeof CAO_EVENT_TYPE_KEYS]",
            "",
        ]
    )
    return "\n".join(lines)


if __name__ == "__main__":
    main()
