"""Generate frontend TypeScript payload types for backend CAO events."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Annotated, Any, Union

from pydantic import Discriminator, TypeAdapter

from cli_agent_orchestrator.events import CaoEvent
from cli_agent_orchestrator.events.serialization import cao_event_kind
from cli_agent_orchestrator.linear.workspace_events import LINEAR_CAO_EVENTS
from cli_agent_orchestrator.runtime.events import RUNTIME_CAO_EVENTS

REPO_ROOT = Path(__file__).resolve().parents[1]
WEB_ROOT = REPO_ROOT / "web"
OUTPUT_PATH = WEB_ROOT / "src" / "generated" / "caoEventPayloadTypes.ts"
OPENAPI_TYPESCRIPT = WEB_ROOT / "node_modules" / ".bin" / "openapi-typescript"

CAO_EVENT_TYPES: tuple[type[CaoEvent], ...] = (*LINEAR_CAO_EVENTS, *RUNTIME_CAO_EVENTS)
CAO_EVENT_PAYLOAD_SCHEMA_NAME = "CaoEventPayload"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated output with the committed file without rewriting it",
    )
    args = parser.parse_args(argv)

    generated = generate_typescript()
    if args.check:
        return _check_output(generated)

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(generated, encoding="utf-8")
    return 0


def generate_typescript() -> str:
    schema_document = _event_openapi_schema_document()
    _assert_schema_covers_registered_events(schema_document)
    with tempfile.TemporaryDirectory(prefix="cao-event-payload-types-", dir=REPO_ROOT) as temp_dir:
        temp_root = Path(temp_dir)
        schema_path = temp_root / "cao-event-payload-schema.json"
        candidate_path = temp_root / "caoEventPayloadTypes.openapi.ts"
        schema_path.write_text(
            json.dumps(schema_document, sort_keys=True, indent=2) + "\n",
            encoding="utf-8",
        )
        subprocess.run(
            [
                str(OPENAPI_TYPESCRIPT),
                str(schema_path),
                "--output",
                str(candidate_path),
            ],
            cwd=WEB_ROOT,
            check=True,
        )
        openapi_types = candidate_path.read_text(encoding="utf-8")
    return _render_generated_module(openapi_types)


def _event_openapi_schema_document() -> dict[str, Any]:
    event_schema = TypeAdapter(
        Annotated[Union[CAO_EVENT_TYPES], Discriminator("kind")]
    ).json_schema(ref_template="#/components/schemas/{model}")
    definitions = event_schema.pop("$defs", {})
    return {
        "openapi": "3.1.0",
        "info": {
            "title": "CAO Event Payload Types",
            "version": "1.0.0",
        },
        "paths": {},
        "components": {
            "schemas": {
                **definitions,
                CAO_EVENT_PAYLOAD_SCHEMA_NAME: event_schema,
            },
        },
    }


def _assert_schema_covers_registered_events(schema_document: dict[str, Any]) -> None:
    payload_schema = schema_document["components"]["schemas"][CAO_EVENT_PAYLOAD_SCHEMA_NAME]
    expected_kinds = {cao_event_kind(event_type) for event_type in CAO_EVENT_TYPES}
    discriminator = payload_schema.get("discriminator")
    if not isinstance(discriminator, dict):
        raise RuntimeError("Generated CAO event payload schema lacks a discriminator")
    mapping = discriminator.get("mapping")
    if not isinstance(mapping, dict):
        raise RuntimeError("Generated CAO event payload schema lacks discriminator mapping")
    actual_kinds = set(mapping)
    if actual_kinds != expected_kinds:
        missing = sorted(expected_kinds - actual_kinds)
        extra = sorted(actual_kinds - expected_kinds)
        raise RuntimeError(
            "Generated CAO event payload schema kind mismatch: "
            f"missing={missing!r} extra={extra!r}"
        )
    one_of = payload_schema.get("oneOf")
    if not isinstance(one_of, list) or len(one_of) != len(expected_kinds):
        raise RuntimeError(
            "Generated CAO event payload schema must contain exactly one branch "
            "per registered event kind"
        )


def _render_generated_module(openapi_types: str) -> str:
    lines = [
        "// Generated by scripts/generate_cao_event_payload_types.py.",
        "// Do not edit by hand.",
        "",
        _strip_openapi_header(openapi_types).rstrip(),
        "",
    ]
    constants = _event_type_constants()
    for name, value in constants.items():
        lines.append(f"export const {name} = {value!r} as const")
    lines.extend(
        [
            "",
            "export const CAO_EVENT_TYPE_KEYS = {",
            *[f"  {name}," for name in constants],
            "} as const",
            "",
            "export type CaoEventTypeKey = typeof CAO_EVENT_TYPE_KEYS[keyof typeof CAO_EVENT_TYPE_KEYS]",
            "",
            "export type CaoEventPayload = components['schemas']['CaoEventPayload']",
            "",
            "export type CaoEventPayloadByTypeKey = {",
            *[
                f"  {event_type_key!r}: Extract<CaoEventPayload, {{ kind: {kind!r} }}>"
                for event_type_key, kind in _event_payload_map_entries()
            ],
            "}",
            "",
            "export type CaoEventPayloadForTypeKey<T extends CaoEventTypeKey> = CaoEventPayloadByTypeKey[T]",
            "",
        ]
    )
    return "\n".join(lines)


def _strip_openapi_header(openapi_types: str) -> str:
    return re.sub(r"^/\*.*?\*/\s*", "", openapi_types, count=1, flags=re.DOTALL)


def _event_type_constants() -> dict[str, str]:
    return {
        _constant_name(event_type.__name__): _public_event_type_key(event_type)
        for event_type in sorted(CAO_EVENT_TYPES, key=lambda event_type: event_type.__name__)
    }


def _event_payload_map_entries() -> tuple[tuple[str, str], ...]:
    return tuple(
        (
            _public_event_type_key(event_type),
            cao_event_kind(event_type),
        )
        for event_type in sorted(CAO_EVENT_TYPES, key=lambda event_type: event_type.__name__)
    )


def _public_event_type_key(event_type: type[CaoEvent]) -> str:
    return f"{event_type.__module__}.{event_type.__qualname__}"


def _constant_name(class_name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", class_name).upper()


def _check_output(generated: str) -> int:
    try:
        existing = OUTPUT_PATH.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"Generated CAO event payload types are missing: {OUTPUT_PATH}", file=sys.stderr)
        return 1
    if existing != generated:
        print(
            "Generated CAO event payload types are stale. "
            "Run `npm run generate:event-types` from web/.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
